// PACKVEDA — Evidence & Sources derivation layer.
//
// Pure, deterministic functions that map an analysis (inputs + engine result +
// material record) to traceable evidence items. The recommendation logic in
// engine.ts is NOT modified or re-run here — this module only records WHERE
// each piece of information came from.
//
// Origin taxonomy (spec §8):
// - source_derived : obtained from a referenced source / database record
// - ai_inferred    : conclusion generated by the PackVeda recommendation engine
// - user_provided  : entered by the user in the analysis wizard
// - estimated      : value unavailable — flagged for supplier / lab follow-up
//
// NO-FABRICATION: every source id must exist in SOURCE_REGISTRY. Values that
// are unavailable render as "Not available" + "Requires supplier/laboratory
// data" — never invented.

import type { AnalysisInput, EngineOutput } from "@/lib/engine";
import type { PackagingMaterial } from "@/lib/data/types";
import { getSource, type ConfidenceLevel, type SourceCategory } from "@/lib/data/sources";

export type InfoOrigin =
  | "source_derived"
  | "ai_inferred"
  | "user_provided"
  | "estimated";

export interface EvidenceItem {
  /** Stable key for rendering */
  id: string;
  /** Human-readable parameter, e.g. "OTR", "Food-contact requirement" */
  parameter: string;
  /** What is claimed (short) */
  claim: string;
  /** Display value — null means "Not available" */
  value: string | null;
  origin: InfoOrigin;
  /** SOURCE_REGISTRY ids backing this item (may be empty) */
  sourceIds: string[];
  /** Extra honesty note, e.g. "Requires supplier/laboratory data" */
  note?: string;
}

export interface EvidenceCoverage {
  supported: number;
  total: number;
  /** null => insufficient data → render "Evidence coverage: Limited" */
  percent: number | null;
}

export type RegulatoryStatus =
  | "checked"
  | "documentation_required"
  | "pending_verification"
  | "not_applicable";

export interface RegulatoryCheck {
  authority: "FSSAI" | "BIS";
  aspect: string;
  status: RegulatoryStatus;
  /** Spec-compliant wording — never "certified" */
  statusLabel: string;
  detail: string;
  sourceIds: string[];
}

export interface AnalysisEvidence {
  items: EvidenceItem[];
  coverage: EvidenceCoverage;
  regulatory: RegulatoryCheck[];
  /** Persisted alongside the analysis for traceability */
  builtAt: string;
}

const INTENSITY_WORD: Record<string, string> = {
  none: "none",
  low: "low",
  moderate: "moderate",
  high: "high",
  very_high: "very high",
  exchange: "gas exchange",
};

function fmt(n: number): string {
  return n.toLocaleString("en-US", { maximumFractionDigits: 1 });
}

/** Highest-level barrier-style requirement key, for the WHY summary. */
function primaryRequirement(result: EngineOutput) {
  const priority = ["oxygen", "moisture", "aroma", "light", "co2", "mechanical", "seal", "thermal"];
  const ranked = [...result.requirements].sort(
    (a, b) =>
      priority.indexOf(a.key) - priority.indexOf(b.key)
  );
  return ranked[0] ?? result.requirements[0] ?? null;
}

// ---------------------------------------------------------------------------
// Evidence builder
// ---------------------------------------------------------------------------

export function buildAnalysisEvidence(
  input: AnalysisInput,
  result: EngineOutput,
  topMaterial: PackagingMaterial | null,
  supplierMatchCount = 0
): AnalysisEvidence {
  const items: EvidenceItem[] = [];

  // ---- 1. Food composition (user-provided in the wizard) ------------------
  items.push({
    id: "ev-composition",
    parameter: "Food composition",
    claim: `Moisture ${fmt(input.moisturePercent)}% · Fat ${fmt(input.fatPercent)}% · pH ${input.ph}${
      input.waterActivity !== null ? ` · a​_w ${input.waterActivity}` : ""
    }`,
    value: `Moisture ${fmt(input.moisturePercent)}%`,
    origin: "user_provided",
    sourceIds: ["usda-fdc", "packveda-commodity-kb"],
    note: "Entered in the analysis wizard; comparable with commodity knowledge-base typical values (USDA FoodData Central).",
  });

  if (input.waterActivity === null) {
    items.push({
      id: "ev-aw-missing",
      parameter: "Water activity (a​_w)",
      claim: "Water activity was not provided for this analysis.",
      value: null,
      origin: "estimated",
      sourceIds: [],
      note: "Value not available in the current knowledge base — moisture-barrier sizing may need supplier or laboratory input.",
    });
  }

  // ---- 2. Derived packaging requirements (engine rules → AI-inferred) ----
  for (const r of result.requirements) {
    const sourceIds =
      r.key === "co2" || (r.key === "moisture" && input.respiration !== "none")
        ? ["packveda-commodity-kb", "fao-postharvest"]
        : r.key === "oxygen" || r.key === "aroma" || r.key === "moisture"
          ? ["packveda-commodity-kb", "packaging-literature"]
          : ["packveda-commodity-kb"];
    items.push({
      id: `ev-req-${r.key}`,
      parameter: r.label,
      claim: r.rationale,
      value: `${INTENSITY_WORD[r.level] ?? r.level} barrier requirement`,
      origin: "ai_inferred",
      sourceIds,
      note: "Derived by PackVeda food-science rules from the inputs above — an inference, not a measured result.",
    });
  }

  // ---- 3. Regulatory ------------------------------------------------------
  items.push({
    id: "ev-fssai",
    parameter: "Food-contact requirement",
    claim: "Food-contact packaging requirements and applicable compliance checks.",
    value: "Aligned with applicable FSSAI requirements — compliance verification required",
    origin: "source_derived",
    sourceIds: ["fssai-packaging"],
    note: "PackVeda is a decision-support system and does not certify packaging materials.",
  });
  items.push({
    id: "ev-bis",
    parameter: "Standard reference",
    claim: "Applicable Indian Standards for the material class.",
    value: "Relevant standard identification pending verification",
    origin: "source_derived",
    sourceIds: ["bis"],
    note: "No specific standard number is claimed — mapping is pending verification.",
  });

  // ---- 4. Material properties (top candidate) -----------------------------
  if (topMaterial) {
    const matSrc =
      topMaterial.sources.length > 0
        ? ["packveda-material-kb", "packaging-literature"]
        : ["packveda-material-kb"];

    const barrier = (
      label: string,
      key: "otr" | "wvtr" | "co2tr",
      unit: string,
      available: boolean
    ): EvidenceItem => {
      const value = topMaterial[key];
      return {
        id: `ev-mat-${key}`,
        parameter: label,
        claim: `${topMaterial.name} — ${label} (indicative class value).`,
        value: value !== null ? `≈ ${fmt(value)} ${unit}` : null,
        origin: value !== null && available ? "source_derived" : "estimated",
        sourceIds: value !== null ? matSrc : [],
        note:
          value !== null
            ? "Indicative knowledge-base value — verify against the supplier datasheet before adoption."
            : "Value not available in the current knowledge base — requires supplier/laboratory data.",
      };
    };

    items.push(barrier("OTR", "otr", "cc/m²/day", topMaterial.otrSourceAvailable));
    items.push(barrier("WVTR", "wvtr", "g/m²/day", topMaterial.wvtrSourceAvailable));
    items.push(barrier("CO₂TR", "co2tr", "cc/m²/day", topMaterial.co2trSourceAvailable));

    items.push({
      id: "ev-mat-tensile",
      parameter: "Mechanical strength",
      claim: `${topMaterial.name} — indicative tensile strength.`,
      value: topMaterial.tensileStrengthMPa !== null ? `${fmt(topMaterial.tensileStrengthMPa)} MPa` : null,
      origin: topMaterial.tensileStrengthMPa !== null ? "source_derived" : "estimated",
      sourceIds: topMaterial.tensileStrengthMPa !== null ? matSrc : [],
      note:
        topMaterial.tensileStrengthMPa !== null
          ? "Indicative knowledge-base value — verify with the supplier datasheet."
          : "Value not available in the current knowledge base — requires supplier/laboratory data.",
    });

    items.push({
      id: "ev-mat-temp",
      parameter: "Temperature range",
      claim: `${topMaterial.name} — indicative service temperature range.`,
      value:
        topMaterial.tempMinC !== null && topMaterial.tempMaxC !== null
          ? `${fmt(topMaterial.tempMinC)} to ${fmt(topMaterial.tempMaxC)} °C`
          : null,
      origin: topMaterial.tempMinC !== null && topMaterial.tempMaxC !== null ? "source_derived" : "estimated",
      sourceIds: topMaterial.tempMinC !== null && topMaterial.tempMaxC !== null ? matSrc : [],
      note:
        topMaterial.tempMinC !== null && topMaterial.tempMaxC !== null
          ? "Indicative knowledge-base value — verify with the supplier datasheet."
          : "Value not available in the current knowledge base — requires supplier/laboratory data.",
    });

    items.push({
      id: "ev-mat-contact",
      parameter: "Food-contact suitability",
      claim: topMaterial.foodContactNote,
      value: topMaterial.foodContactSuitable ? "Suitable material class — verify grade" : "Not established",
      origin: "source_derived",
      sourceIds: ["packveda-material-kb", "fssai-packaging"],
      note: "Material-class statement — food-contact grade must be confirmed with the supplier.",
    });

    // ---- 5. The recommendation itself (pure AI inference) -----------------
    items.push({
      id: "ev-recommendation",
      parameter: "Packaging recommendation",
      claim: `${result.recommended?.materialName ?? topMaterial.name} recommended for this profile.`,
      value: `Engine score ${result.recommended?.score.toFixed(1) ?? "—"}/100`,
      origin: "ai_inferred",
      sourceIds: [],
      note: "AI inference based on the cited inputs and knowledge-base properties — decision support, not a guarantee.",
    });
  }

  // ---- 6. Supplier-declared data (awaiting verification) ------------------
  if (supplierMatchCount > 0) {
    items.push({
      id: "ev-suppliers",
      parameter: "Supplier availability",
      claim: `${supplierMatchCount} supplier listing${supplierMatchCount === 1 ? "" : "s"} matched against the derived requirements.`,
      value: `${supplierMatchCount} matched listing${supplierMatchCount === 1 ? "" : "s"}`,
      origin: "source_derived",
      sourceIds: ["supplier-datasheets"],
      note: "Supplier-declared properties are awaiting verification against original datasheets or laboratory tests.",
    });
  }

  // ---- Coverage ------------------------------------------------------------
  // A claim is "supported" when it traces to at least one registry source or
  // to the user's own inputs. Pure estimates / unavailable values are not.
  const supported = items.filter(
    (i) => i.sourceIds.length > 0 || i.origin === "user_provided"
  ).length;
  const total = items.length;
  const percent =
    total >= 4 ? Math.round((supported / Math.max(1, total)) * 100) : null;

  // ---- Regulatory checks ---------------------------------------------------
  const regulatory: RegulatoryCheck[] = [
    {
      authority: "FSSAI",
      aspect: "Food-contact packaging requirements",
      status: "documentation_required",
      statusLabel: "Documentation required",
      detail:
        "Aligned with applicable FSSAI requirements for food-contact packaging. PackVeda does not certify materials — obtain and retain food-grade compliance documentation from the supplier.",
      sourceIds: ["fssai-packaging"],
    },
    {
      authority: "BIS",
      aspect: "Applicable Indian Standards",
      status: "pending_verification",
      statusLabel: "Pending verification",
      detail:
        "Relevant BIS standard identification is pending verification for this material class. Check the Bureau of Indian Standards portal or ask the supplier for applicable standard declarations.",
      sourceIds: ["bis"],
    },
  ];

  return { items, coverage: { supported, total, percent }, regulatory, builtAt: new Date().toISOString() };
}

// ---------------------------------------------------------------------------
// Structured "WHY THIS MATERIAL?" summary (spec §6)
// ---------------------------------------------------------------------------

export interface WhyRow {
  label: string;
  value: string;
  origin: InfoOrigin;
  sourceIds: string[];
}

export function buildWhyThisMaterial(
  input: AnalysisInput,
  result: EngineOutput,
  topMaterial: PackagingMaterial | null,
  supplierMatchCount = 0
): WhyRow[] {
  const primary = primaryRequirement(result);
  const rows: WhyRow[] = [
    {
      label: "Food",
      value: `${input.commodityName}${input.foodCategory ? ` — ${input.foodCategory}` : ""}`,
      origin: "user_provided",
      sourceIds: ["usda-fdc", "packveda-commodity-kb"],
    },
    {
      label: "Observed requirement",
      value: primary
        ? `${primary.label}: ${INTENSITY_WORD[primary.level] ?? primary.level} — derived from the food profile`
        : "Packaging requirements derived from the food profile",
      origin: "ai_inferred",
      sourceIds: ["packveda-commodity-kb"],
    },
    {
      label: "Storage",
      value: `${input.storageType.replace("_", " ")} · ${fmt(input.storageTempC)} °C · RH ${fmt(input.storageRH)}% · target ${input.targetShelfLifeDays} days`,
      origin: "user_provided",
      sourceIds: [],
    },
  ];

  if (topMaterial) {
    const barrierBits: string[] = [];
    if (topMaterial.otr !== null) barrierBits.push(`OTR ≈ ${fmt(topMaterial.otr)} cc/m²/day`);
    if (topMaterial.wvtr !== null) barrierBits.push(`WVTR ≈ ${fmt(topMaterial.wvtr)} g/m²/day`);
    rows.push({
      label: "Material characteristic",
      value:
        (primary ? `${topMaterial.name} — matches the ${primary.label.toLowerCase()} requirement` : topMaterial.name) +
        (barrierBits.length ? ` (${barrierBits.join(" · ")})` : ""),
      origin: "source_derived",
      sourceIds: ["packveda-material-kb", "packaging-literature"],
    });
    rows.push({
      label: "Regulatory compatibility",
      value: topMaterial.foodContactSuitable
        ? "Food-contact documentation available for the material class — verification required"
        : "Food-contact suitability not established for this material class",
      origin: "source_derived",
      sourceIds: ["fssai-packaging"],
    });
    rows.push({
      label: "Supplier availability",
      value:
        supplierMatchCount > 0
          ? `Available from ${supplierMatchCount} matched supplier listing${supplierMatchCount === 1 ? "" : "s"}`
          : "No supplier match recorded yet — explore the marketplace",
      origin: supplierMatchCount > 0 ? "source_derived" : "ai_inferred",
      sourceIds: supplierMatchCount > 0 ? ["supplier-datasheets"] : [],
    });
  }

  return rows;
}

// ---------------------------------------------------------------------------
// Persistence shape (analysis_sources table / API payload)
// ---------------------------------------------------------------------------

export interface AnalysisSourceRow {
  sourceType: SourceCategory;
  sourceName: string;
  title: string;
  description: string;
  url: string | null;
  publicationYear: number | null;
  sourceVersion: string | null;
  parameterSupported: string;
  confidenceLevel: ConfidenceLevel;
  parameter: string;
  claim: string;
  value: string | null;
  origin: InfoOrigin;
}

/** Flatten evidence items into per-source rows for structured persistence. */
export function toSourceRows(evidence: AnalysisEvidence): AnalysisSourceRow[] {
  const rows: AnalysisSourceRow[] = [];
  for (const item of evidence.items) {
    if (item.sourceIds.length === 0) continue;
    for (const id of item.sourceIds) {
      const src = getSource(id);
      if (!src) continue;
      rows.push({
        sourceType: src.category,
        sourceName: src.fullName,
        title: src.title ?? "",
        description: src.description,
        url: src.url,
        publicationYear: src.publicationYear,
        sourceVersion: src.version,
        parameterSupported: src.parameters.join(","),
        confidenceLevel: src.confidence,
        parameter: item.parameter,
        claim: item.claim,
        value: item.value,
        origin: item.origin,
      });
    }
  }
  return rows;
}
